/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer-setup.glb -o src/components/ModelComputer.tsx -t -r public 
Author: LagzDesign (https://sketchfab.com/LagzDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-low-poly-caffb0d42a594ac2b67970af07d10a5f
Title: Gaming Setup (low-poly)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function ModelComputer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/computer-setup.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.349}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.003, 2.671, -2.527]} rotation={[Math.PI / 2, 0, 0]} scale={0.506}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.005']} />
          </group>
          <group position={[-0.766, 2.587, -0.992]} rotation={[Math.PI / 2, 0, 0.153]} scale={1.552}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.plastic} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.screen} />
          </group>
          <group position={[-0.567, 2.587, 1.437]} rotation={[Math.PI / 2, 0, -0.324]} scale={1.552}>
            <mesh geometry={nodes.Object_17.geometry} material={materials.plastic} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.screen} />
          </group>
          <group position={[2.387, 0, -0.364]} rotation={[Math.PI / 2, 0, 2.27]} scale={0.82}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.013']} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.006']} position={[-0.766, 2.587, -0.992]} rotation={[Math.PI / 2, 0, 0.153]} scale={1.552} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.006']} position={[-0.567, 2.587, 1.437]} rotation={[Math.PI / 2, 0, -0.324]} scale={1.552} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} position={[0.528, 2.599, 0.413]} rotation={[Math.PI / 2, 0, -1.607]} scale={0.782} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material.008']} position={[0.527, 2.609, -1.063]} rotation={[Math.PI / 2, 0, -1.405]} scale={0.187} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Material} position={[0.457, 2.595, 0]} scale={[0.582, 1, 1.832]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-setup.glb')
