/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { JSX } from 'react' // Hapus useEffect, useState, Html
import { useGLTF } from '@react-three/drei' 
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh; Object_3: THREE.Mesh; Object_4: THREE.Mesh; Object_5: THREE.Mesh;
    Object_6: THREE.Mesh; Object_7: THREE.Mesh; Object_8: THREE.Mesh; Object_9: THREE.Mesh;
    Object_10: THREE.Mesh; Object_11: THREE.Mesh; Object_12: THREE.Mesh; Object_13: THREE.Mesh;
  }
  materials: {
    Desk_1: THREE.MeshStandardMaterial; Posters: THREE.MeshStandardMaterial; Keyboard: THREE.MeshStandardMaterial;
    speaker_2: THREE.MeshStandardMaterial; BG_Dark: THREE.MeshStandardMaterial; Carpet: THREE.MeshStandardMaterial;
    Emission: THREE.MeshStandardMaterial; Emission_Blue: THREE.MeshStandardMaterial; Foam_Acoustic: THREE.MeshStandardMaterial;
    Trim_Sheet_Wall: THREE.MeshStandardMaterial; Monitor_Single: THREE.MeshStandardMaterial;
  }
}

export function ModelRoom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/computer-room.glb') as unknown as GLTFResult
  
  // Tidak ada logic scroll/focus lagi disini.
  // Room ini sekarang murni dekorasi visual.

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Desk_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Posters} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.speaker_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BG_Dark} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Carpet} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Emission} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Emission_Blue} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Foam_Acoustic} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Foam_Acoustic} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Trim_Sheet_Wall} />

        {/* === MONITOR SCREEN (Object_13) === */}
        <mesh geometry={nodes.Object_13.geometry} material={materials.Monitor_Single} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-room.glb')